version: 0.0
os: linux
files:
  - source: /    # This should copy everything from the root of the GitHub repository
    destination: /home/ec2-user/myapp/  # Ensure this is where you want the files

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Install dependencies
      runas: root
  AfterInstall:
    - location: scripts/start_app.sh  # Start app
      runas: ec2-user
