version: 0.0
os: linux
files:
  - source: /   # Copy everything from the root of the GitHub repository
    destination: /home/ec2-user/myapp/  # Copy to this directory on EC2
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Install dependencies before app installation
      runas: root
  AfterInstall:
    - location: scripts/start_app.sh  # Start the app after installation
      runas: ec2-user
