version: 0.0
os: linux
files:
  - source: /    # This copies everything from the root of the GitHub repository
    destination: /home/ec2-user/myapp/  # Destination on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script to install dependencies
      runas: root  # Run as root
  AfterInstall:
    - location: scripts/start_app.sh  # Script to start the Node.js app
      runas: ec2-user  # Run as ec2-user
